//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadComerWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catálogo
    {
        public int IdP { get; set; }
        public string RFC { get; set; }
        public Nullable<float> Precio { get; set; }
    
        public virtual Cadena Cadena { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
